---
apiVersion: v1
kind: Service
metadata:
  name: cbg-website-dev
  namespace: cbg-dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: cbg-website-dev